### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by wangyunzi** [Meayair/Typecho-Theme-MeaWord#1]
点击后台个人评论后手机端打开右侧是空白的，手机端文章中链接太长了就看不到了。
![IMG_1748.jpg](https://bu.dusays.com/2024/01/23/65af108065fe0.jpg)
![IMG_1749.jpg](https://bu.dusays.com/2024/01/23/65af108098727.jpg)

**Comment by Meayair** [comment]
已经修复~
