### ISSUE TITLE
首页”自动截取标题首个文字作为列表中的文章背景“不显示

### ISSUE THREAD

**Issue by hevuan** [Meayair/Typecho-Theme-MeaWord#4]
截图：https://yp.bayea.org/view.php/382e6362b48d5535f235b302f72245ca.png

首页”自动截取标题首个文字作为列表中的文章背景“不显示，但内容页显示。

**Comment by Meayair** [comment]
发布文章时，把最下面“特色图像”清空，或者填写图片链接[其他用户的情况](https://www.bawge.com/archives/63.html#comment-94)
