### ISSUE TITLE
有些不会自动截取标题首个文字作为列表中的文章的背景

### ISSUE THREAD

**Issue by kshipeng** [Meayair/Typecho-Theme-MeaWord#5]
有些不会自动截取标题首个文字作为列表中的文章的背景。
[https://blog.isgo.win](https://blog.isgo.win)

**Comment by Meayair** [comment]
发布文章时，把最下面“特色图像”清空，或者填写图片链接[其他用户的情况](https://www.bawge.com/archives/63.html#comment-94)

**Comment by kshipeng** [comment]
明白了。谢谢
